---
- name: Dump all vars
  template: src=dumpme.j2 dest={{ kxlops_dumpme_guest_destination }}

- name: Retrieve dumpfile
  fetch: "src={{ kxlops_dumpme_guest_destination }} dest={{ kxlops_dumpme_host_destination }} flat={{ kxlops_dumpme_flat_mode }}"
  when: kxlops_dumpme_host_destination is defined

- name: Remove dumpfile on the guest
  file: path={{ kxlops_dumpme_guest_destination }} state=absent
  when: kxlops_dumpme_host_destination is defined and kxlops_dumpme_remove_host_file == true